werw

diff --git a/.github/workflows/hook.yml b/.github/workflows/hook.yml
--- a/.github/workflows/hook.yml
+++ b/.github/workflows/hook.yml
@@ -18,11 +18,17 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Step 2: Build
+      - name: Step 1 Run some tests
+        id: step1
+        run: |
+          echo "Running Step 1"
+          exit 1  # Simulate failure
+
+      - name: Step 2 Build
         id: step2
         run: echo "Building project"
 
-      - name: Step 3: Deploy
+      - name: Step 3 Deploy
         id: step3
         run: echo "Deploying project"
 
